import { MaintenanceTask, createTask } from '../models/Task';

/**
 * Predefined maintenance tasks that ship with the app.
 * Users can modify or disable these, and add their own.
 */
export const DEFAULT_TASKS: Omit<MaintenanceTask, 'id' | 'createdAt' | 'updatedAt' | 'completionHistory' | 'nextDueDate'>[] = [
    {
        title: 'Water Change (10-20%)',
        description: 'Replace 10-20% of tank water with fresh saltwater mixed to the correct salinity.',
        recurrenceInterval: 7,
        recurrenceUnit: 'days',
        reminderOffsetHours: 24,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Test Water Parameters',
        description: 'Test salinity, pH, ammonia, nitrite, nitrate, calcium, alkalinity, and magnesium.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 12,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Clean Glass / Algae Scrub',
        description: 'Scrub inside glass panels to remove algae buildup.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 12,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Feed Corals',
        description: 'Target-feed corals with phytoplankton, amino acids, or coral food.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Top Off (ATO Check)',
        description: 'Check auto-top-off system or manually top off evaporated water with RODI.',
        recurrenceInterval: 1,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Clean Filter Socks / Media',
        description: 'Replace or rinse filter socks and check mechanical filtration media.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 24,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Dose Calcium & Alkalinity',
        description: 'Check and dose calcium, alkalinity, and magnesium as needed.',
        recurrenceInterval: 1,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Clean Protein Skimmer',
        description: 'Empty skimmer cup and clean the neck for optimal skimming.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 12,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Inspect Livestock Health',
        description: 'Visually inspect all fish, corals, and invertebrates for signs of disease or stress.',
        recurrenceInterval: 1,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Clean Pumps & Powerheads',
        description: 'Remove and soak pumps/powerheads in vinegar to remove calcium deposits.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Replace Carbon / GFO Media',
        description: 'Swap out activated carbon and/or GFO (granular ferric oxide) media in the reactor.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
    },
    {
        title: 'Calibrate Probes',
        description: 'Calibrate pH, salinity, and ORP probes with reference solutions.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
    },
];
