import { Creature } from '../models/Creature';

/**
 * Predefined sample creatures that ship with the app.
 * Represents a realistic mixed reef aquarium stocking list.
 * Users can modify, archive, or delete these and add their own.
 */
export const DEFAULT_CREATURES: Omit<Creature, 'id' | 'createdAt' | 'updatedAt' | 'dateAcquired'>[] = [
    // ── Fish ──────────────────────────────────────────────
    {
        name: 'Nemo',
        species: 'Ocellaris Clownfish (Amphiprion ocellaris)',
        type: 'fish',
        quantity: 2,
        notes: 'Mated pair – hosting the Bubble Tip Anemone. Hardy and reef-safe.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Flash',
        species: 'Royal Gramma (Gramma loreto)',
        type: 'fish',
        quantity: 1,
        notes: 'Peaceful, stays near rock work. Great purple & yellow coloration.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Blaze',
        species: 'Flame Angelfish (Centropyge loricula)',
        type: 'fish',
        quantity: 1,
        notes: 'May nip at LPS corals – monitor closely. Feeds on algae and mysis.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Dart',
        species: 'Firefish Goby (Nemateleotris magnifica)',
        type: 'fish',
        quantity: 1,
        notes: 'Shy jumper – needs a tight-fitting lid. Beautiful red/white gradient.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Blenny',
        species: 'Tailspot Blenny (Ecsenius stigmatura)',
        type: 'fish',
        quantity: 1,
        notes: 'Algae grazer, perches on rocks. Tons of personality.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Tang',
        species: 'Yellow Tang (Zebrasoma flavescens)',
        type: 'fish',
        quantity: 1,
        notes: 'Needs a tank of 75 gal+. Excellent algae eater, feeds on nori sheets.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Mandarin',
        species: 'Green Mandarin Dragonet (Synchiropus splendidus)',
        type: 'fish',
        quantity: 1,
        notes: 'Requires a mature tank with copepod population. Slow, deliberate feeder.',
        healthLog: [],
        archived: false,
    },

    // ── Corals ────────────────────────────────────────────
    {
        name: 'Hammer Colony',
        species: 'Hammer Coral (Euphyllia ancora)',
        type: 'coral',
        quantity: 1,
        notes: 'LPS – medium flow, moderate light. Sweeper tentacles can sting neighbors.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Frogspawn',
        species: 'Frogspawn Coral (Euphyllia divisa)',
        type: 'coral',
        quantity: 1,
        notes: 'LPS – similar care to Hammer. Give 6″ spacing from other corals.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Zoa Garden',
        species: 'Zoanthid (Zoanthus sp.)',
        type: 'coral',
        quantity: 12,
        notes: 'Mixed color morphs on a frag plug. Low-moderate light, low flow. Handle with gloves (palytoxin).',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Montipora Cap',
        species: 'Montipora capricornis',
        type: 'coral',
        quantity: 1,
        notes: 'SPS – plating growth form, needs stable alk/cal and high light.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Green Slimer',
        species: 'Acropora yongei',
        type: 'coral',
        quantity: 1,
        notes: 'SPS – fast grower under high light & strong flow. Good beginner Acro.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Duncan Colony',
        species: 'Duncan Coral (Duncanopsammia axifuga)',
        type: 'coral',
        quantity: 1,
        notes: 'LPS – feeds well on mysis. Low-moderate light, moderate flow.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Candy Cane',
        species: 'Candy Cane Coral (Caulastrea furcata)',
        type: 'coral',
        quantity: 1,
        notes: 'Beginner-friendly LPS. Moderate light, low flow. Responds well to target feeding.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Torch Coral',
        species: 'Torch Coral (Euphyllia glabrescens)',
        type: 'coral',
        quantity: 1,
        notes: 'LPS – medium flow, moderate light. Long sweeper tentacles, needs space.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Mushroom Rock',
        species: 'Rhodactis / Discosoma sp.',
        type: 'coral',
        quantity: 5,
        notes: 'Soft coral – very hardy. Low light, low flow. Spreads easily.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'GSP Mat',
        species: 'Green Star Polyps (Pachyclavularia violacea)',
        type: 'coral',
        quantity: 1,
        notes: 'Soft coral – fast grower, keep on an isolated rock or back wall to prevent takeover.',
        healthLog: [],
        archived: false,
    },

    // ── Invertebrates ─────────────────────────────────────
    {
        name: 'CUC Snails',
        species: 'Trochus / Nassarius Snail Mix',
        type: 'invertebrate',
        quantity: 15,
        notes: 'Clean-up crew – Trochus eat algae on glass/rocks, Nassarius sift sand.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Hermits',
        species: 'Blue Leg Hermit Crab (Clibanarius tricolor)',
        type: 'invertebrate',
        quantity: 10,
        notes: 'Clean-up crew – keep extra empty shells so they don\'t attack snails.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Peppermint Shrimp',
        species: 'Peppermint Shrimp (Lysmata wurdemanni)',
        type: 'invertebrate',
        quantity: 2,
        notes: 'Eats Aiptasia anemones. Nocturnal – hides in rock work during the day.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Skunk Cleaner',
        species: 'Skunk Cleaner Shrimp (Lysmata amboinensis)',
        type: 'invertebrate',
        quantity: 1,
        notes: 'Cleaning station for fish. Hand-feeds readily. Sensitive to copper.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Rose Bubble Tip',
        species: 'Bubble Tip Anemone (Entacmaea quadricolor)',
        type: 'invertebrate',
        quantity: 1,
        notes: 'Hosts the clownfish pair. Needs stable params and moderate-high light. May wander.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Tuxedo Urchin',
        species: 'Tuxedo Urchin (Mespilia globulus)',
        type: 'invertebrate',
        quantity: 1,
        notes: 'Excellent algae grazer. Carries fragments and shells on its back. Reef-safe.',
        healthLog: [],
        archived: false,
    },
    {
        name: 'Emerald Crab',
        species: 'Emerald Crab (Mithraculus sculptus)',
        type: 'invertebrate',
        quantity: 2,
        notes: 'Eats bubble algae (Valonia). Generally reef-safe but may nip corals if underfed.',
        healthLog: [],
        archived: false,
    },
];
