import { MaintenanceTask } from '../models/Task';

/**
 * Predefined maintenance tasks that ship with the app.
 * Users can modify or disable these, and add their own.
 */
export const DEFAULT_TASKS: Omit<MaintenanceTask, 'id' | 'createdAt' | 'updatedAt' | 'completionHistory' | 'nextDueDate'>[] = [
    // ── Tank-scoped tasks ──────────────────────────────────
    {
        title: 'Water Change (10-20%)',
        description: 'Replace 10-20% of tank water with fresh saltwater mixed to the correct salinity.',
        recurrenceInterval: 7,
        recurrenceUnit: 'days',
        reminderOffsetHours: 24,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Test Water Parameters',
        description: 'Test salinity, pH, ammonia, nitrite, nitrate, calcium, alkalinity, and magnesium.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 12,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Clean Glass / Algae Scrub',
        description: 'Scrub inside glass panels to remove algae buildup.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 12,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Feed Corals',
        description: 'Target-feed corals with phytoplankton, amino acids, or coral food.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Top Off (ATO Check)',
        description: 'Check auto-top-off system or manually top off evaporated water with RODI.',
        recurrenceInterval: 1,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Clean Filter Socks / Media',
        description: 'Replace or rinse filter socks and check mechanical filtration media.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 24,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Dose Calcium & Alkalinity',
        description: 'Check and dose calcium, alkalinity, and magnesium as needed.',
        recurrenceInterval: 1,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Clean Protein Skimmer',
        description: 'Empty skimmer cup and clean the neck for optimal skimming.',
        recurrenceInterval: 3,
        recurrenceUnit: 'days',
        reminderOffsetHours: 12,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Inspect Livestock Health',
        description: 'Visually inspect all fish, corals, and invertebrates for signs of disease or stress.',
        recurrenceInterval: 1,
        recurrenceUnit: 'days',
        reminderOffsetHours: 6,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Clean Pumps & Powerheads',
        description: 'Remove and soak pumps/powerheads in vinegar to remove calcium deposits.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Replace Carbon / GFO Media',
        description: 'Swap out activated carbon and/or GFO (granular ferric oxide) media in the reactor.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },
    {
        title: 'Calibrate Probes',
        description: 'Calibrate pH, salinity, and ORP probes with reference solutions.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
    },

    // ── Global tasks (cross-tank) ──────────────────────────
    {
        title: 'Mix Saltwater Batch',
        description: 'Mix RODI + reef salt to target salinity. Aerate & heat 24h before use.',
        recurrenceInterval: 1,
        recurrenceUnit: 'weeks',
        reminderOffsetHours: 24,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'global',
    },
    {
        title: 'Check RODI Filter TDS',
        description: 'Test TDS of RODI output. Replace filters/membrane when >5 TDS.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'global',
    },
    {
        title: 'Inspect Equipment',
        description: 'Check return pump, heater, ATO, powerheads for wear or malfunction.',
        recurrenceInterval: 1,
        recurrenceUnit: 'months',
        reminderOffsetHours: 48,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'global',
    },

    // ── Triggered tasks (per-tank, threshold-based) ────────
    {
        title: 'Emergency Water Change',
        description: 'Ammonia detected — perform 25-50% water change immediately.',
        recurrenceInterval: undefined,
        recurrenceUnit: undefined,
        reminderOffsetHours: 0,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
        triggerThreshold: {
            parameterId: 'ammonia',
            operator: 'above',
            value: 0.25,
        },
    },
    {
        title: 'Reduce Nitrates',
        description: 'Nitrates elevated — increase water changes or adjust feeding.',
        recurrenceInterval: undefined,
        recurrenceUnit: undefined,
        reminderOffsetHours: 0,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
        triggerThreshold: {
            parameterId: 'nitrate',
            operator: 'above',
            value: 20,
        },
    },
    {
        title: 'Dose Alkalinity',
        description: 'Alkalinity low — dose buffer per calculator. Retest in 4 hours.',
        recurrenceInterval: undefined,
        recurrenceUnit: undefined,
        reminderOffsetHours: 0,
        notificationsEnabled: true,
        isPredefined: true,
        tankId: null,
        scope: 'tank',
        triggerThreshold: {
            parameterId: 'alkalinity',
            operator: 'below',
            value: 7,
        },
    },
];
